# Generated by Django 5.2.3 on 2025-06-29 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('path', models.FilePathField(path='uploads', recursive=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
